<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $report->report_name }}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        :root {
            --bg: #f3f4f6;
            --card: #ffffff;
            --text: #111827;
            --muted: #6b7280;
            --accent: #1e40af;
            --accent-2: #3b82f6;
            --border: #e5e7eb;
        }

        html, body {
            margin: 0;
            padding: 0;
            font-family: 'DejaVu Sans', system-ui, sans-serif;
            background-color: var(--bg);
            color: var(--text);
        }

        .page {
            max-width: 900px;
            margin: 20px auto;
            background: var(--card);
            border-radius: 12px;
            border: 1px solid var(--border);
            box-shadow: 0 4px 20px rgba(0,0,0,0.05);
            padding: 24px;
        }

        header.report-header {
            display: flex;
            align-items: center;
            gap: 16px;
            border-bottom: 1px solid var(--border);
            padding-bottom: 16px;
        }

        .logo {
            width: 72px;
            height: 72px;
            background: linear-gradient(135deg, var(--accent-2), #9333ea);
            color: #fff;
            font-weight: 700;
            font-size: 28px;
            border-radius: 12px;
            display: flex;
            align-items: center;
            justify-content: center;
            flex-shrink: 0;
        }

        .title-area h1 {
            margin: 0;
            font-size: 22px;
            color: var(--accent);
        }

        .meta {
            font-size: 13px;
            color: var(--muted);
            margin-top: 4px;
        }

        .actions {
            margin-left: auto;
            text-align: right;
            font-size: 13px;
            color: var(--muted);
        }

        .section-row {
            display: flex;
            gap: 20px;
            margin-top: 20px;
        }

        .card {
            background: var(--card);
            border: 1px solid var(--border);
            border-radius: 10px;
            padding: 16px;
            box-shadow: 0 2px 6px rgba(0,0,0,0.05);
            flex: 1;
        }

        .card h2 {
            margin: 0 0 12px 0;
            font-size: 18px;
            color: var(--accent);
        }

        .overview-list p {
            margin: 6px 0;
            font-size: 14px;
            color: var(--text);
        }

        .small { font-size: 13px; color: var(--muted); }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 12px;
            font-size: 14px;
        }

        thead th {
            background: #f9fafb;
            text-align: left;
            padding: 10px;
            border-bottom: 1px solid var(--border);
            font-weight: 600;
            color: var(--accent);
        }

        tbody td {
            padding: 12px;
            border-bottom: 1px solid #f1f5f9;
        }

        tbody tr:nth-child(even) {
            background: #fdfdfd;
        }

        .badge {
            display: inline-block;
            padding: 5px 10px;
            border-radius: 999px;
            font-size: 12px;
            font-weight: 600;
            color: #fff;
        }

        .badge-normal { background: #6b7280; }
        .badge-high { background: #f97316; }
        .badge-urgent { background: #dc2626; }
        .badge-low { background: #10b981; }

        footer {
            margin-top: 24px;
            border-top: 1px dashed var(--border);
            padding-top: 12px;
            text-align: center;
            font-size: 13px;
            color: var(--muted);
        }

        @media(max-width:720px){
            .section-row { flex-direction: column; }
            header.report-header { flex-direction: column; align-items: flex-start; gap: 12px; }
            .actions { text-align: left; }
        }
    </style>
</head>
<body>
<div class="page">
    <header class="report-header">
        <div class="logo">R</div>
        <div class="title-area">
            <h1>{{ $report->report_name ?? 'Untitled Report' }}</h1>
            <div class="meta">Type: {{ ucfirst($report->report_type ?? 'general') }} • Generated by: {{ $report->generated_by ?? 'Admin' }}</div>
            <div class="meta">Created on: {{ $report->created_at ? $report->created_at->format('M d, Y') : '-' }}</div>
            <div class="actions">Report ID: <strong>#{{ $report->report_id ?? '—' }}</strong></div>
        </div>

    </header>

    <div class="section-row">
        <div class="card">
            <h2>Report Overview</h2>
            <div class="overview-list small">
                <p><strong>Type:</strong> {{ ucfirst($report->report_type ?? '-') }}</p>
                <p><strong>Description:</strong> {{ $report->description ?? '-' }}</p>
                <p><strong>Special Instructions:</strong> {{ $report->special_instructions ?? '-' }}</p>
            </div>
        </div>

        <div class="card" style="flex: 0 0 260px;">
            <h2>Summary</h2>
            <p class="small"><strong>Department:</strong><br>{{ $department ?? '-' }}</p>
            <p class="small"><strong>Employee:</strong><br>{{ $employee ?? '-' }}</p>
            <p class="small"><strong>Period:</strong><br>{{ $report->start_date ?? '-' }} — {{ $report->end_date ?? '-' }}</p>
            <p class="small" style="margin-top: 8px;"><strong>Priority:</strong><br>
                @php $priority = strtolower($report->priority ?? 'normal'); @endphp
                <span class="badge badge-{{ $priority }}">{{ ucfirst($priority) }}</span>
            </p>
        </div>
    </div>

    <div class="card" style="margin-top: 20px;">
        <h2>Report Details</h2>
        <table>
            <thead>
            <tr>
                <th>Department</th>
                <th>Employee</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Priority</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>{{ $department ?? '-' }}</td>
                <td>{{ $employee ?? '-' }}</td>
                <td>{{ $report->start_date ?? '-' }}</td>
                <td>{{ $report->end_date ?? '-' }}</td>
                <td><span class="badge badge-{{ $priority }}">{{ ucfirst($priority) }}</span></td>
            </tr>
            </tbody>
        </table>
    </div>

    <footer>
        Generated by {{ $report->generated_by ?? 'Admin' }} • {{ now()->format('M d, Y H:i') }}
    </footer>
</div>
</body>
</html>
